image:
  repository: bitnami/mongodb
  tag: 4.0.27-debian-9-r118
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi

mongodb:
  username: newman
  password: newman
  database: newman-db

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  storageClass: gp3
  
tolerations: []  # Define tolerations if needed for running on specific nodes
