environment:
  matrix:
  - nodejs_version: "6.0"
  - nodejs_version: "4.0"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - cd tests
  - npm install -g elm@0.18.0 elm-test@0.18.3 elm-format@exp
  - npm install
  - elm-package install --yes

test_script:
  - npm test

build: off
