---
# This role deploys/re-deploys newman agent
- name: "create newman folder if not exists"
  shell: mkdir -p {{agent_home_dir}}
- name: "remove old agents log if exists"
  shell: rm -f {{agent_home_dir}}/nohup*
  ignore_errors: yes

- name: "copy  newman agent script"
  copy: src={{newman_local_dir}}/ansible/roles/ie_agent_deploy/files/newman-agent.sh dest={{agent_home_dir}} owner=xap mode=0777

- name: "install python-setuptools"
  yum: name=python-setuptools-0.9.8

- name: "easy install pip"
  shell: sudo easy_install pip

- name: "install meld3"
  shell: sudo pip install meld3

- name: "install supervisord"
  shell: sudo pip install supervisor

- name: "create supervisord.conf file"
  shell: echo_supervisord_conf > {{agent_home_dir}}/supervisord.conf

- name: "copy newman_agent program to tmp file"
  copy: src={{newman_local_dir}}/ansible/roles/ie_agent_deploy/files/newman_agent.conf dest={{agent_home_dir}} owner=xap mode=0777

- name: "append newman_agent program to supervisord.conf"
  shell: cat /home/xap/newman-agent/newman_agent.conf >> /home/xap/newman-agent/supervisord.conf

- name: "rm newman_agent file"
  shell: rm -f /home/xap/newman-agent/newman_agent.conf

- name: "create directory for supervisord logs"
  shell: mkdir -p {{agent_home_dir}}/supervisord_logs

- name: "remove supervisord logs file"
  shell: rm -f {{agent_home_dir}}/supervisord_logs/*
  ignore_errors: yes

- name: "create supervisord err file"
  shell: touch {{agent_home_dir}}/supervisord_logs/err.log

- name: "create supervisord out file"
  shell: touch {{agent_home_dir}}/supervisord_logs/out.log

- name: "deploy new agent jar"
  copy: src={{newman_local_dir}}/newman-agent/target/newman-agent-1.0.jar dest={{agent_home_dir}} owner=xap mode=0777
  tags:
    - deploy

- name: "restart agent machine"
  command: init 6
  async: 0
  poll: 0
  sudo: true
  ignore_errors: true

- name: "waiting for agent machine to come back"
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=15 state=started
  sudo: false

- name: "ensure agent started"
  command: cat /home/xap/newman-agent/nohup_agent1.out
  register: log_output
  until: log_output.stdout.find("Agent is initializing") > -1
  retries: 5
  delay: 10

