---
# This role installs newman locally
#  command: "{{maven_cmd}} clean install -Dmaven.repo.local={{local_maven_repo}}"
- name: mvn install newman project
command: "mvn clean install"
  args:
    chdir: "../"
  tags:
    - local