apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo-server
data:
  mongodb.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
      port: 27017
    systemLog:
      destination: file
      path: /logs/mongodb.log      
      logAppend: true
      verbosity: 0
    security:
      authorization: enabled