apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pvc"
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo-server
spec:
  accessModes: {{ .Values.persistence.accessModes | toJson }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}