apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongo-server
spec:
  serviceName: mongo-server-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongo-server
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      initContainers:
        - name: init-mongo-config
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /config/mongodb.conf /etc/mongo/mongodb.conf
          volumeMounts:
            - name: config-volume              
              mountPath: /config
            - name: mongo-config
              mountPath: /etc/mongo
      containers:
        - name: mongo-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGODB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password | quote }}
            - name: MONGODB_USERNAME
              value: {{ .Values.mongodb.username | quote }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password | quote }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.database | quote }}
          command:
            - mongod
            - "--config"
            - /etc/mongo/mongodb.conf
          volumeMounts:
            - name: mongo-data
              mountPath: "/data/db"
            - name: mongo-config
              mountPath: "/etc/mongo/"
      volumes:
      - name: config-volume
        configMap:
          name: "{{ .Release.Name }}-config"    
      securityContext:
        fsGroup: 1001
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: mongo-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
