replicaCount: 1

image:
  repository: 573366771204.dkr.ecr.us-east-1.amazonaws.com/newman/newman-server
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: newman-server.gigaspaces.net
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

persistence:
  enabled: true
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: gp3

mongodb:
  host: mongo-server
  port: 27017
