---
# This role deploys/re-deploys newman agent
- name: "create newman folder if not exists"
  shell: mkdir -p {{agent_home_dir}}
- name: "remove old agents log if exists"
  shell: rm -f {{agent_home_dir}}/nohup*
  ignore_errors: yes
- name: "undeploy old agents"
  script: "{{newman_local_dir}}/ansible/roles/agent_deploy/files/stop-newman-agent.sh"
  ignore_errors: yes
- name: "deploy new agent jar"
  copy: src={{newman_local_dir}}/newman-agent/target/newman-agent-1.0.jar dest={{agent_home_dir}} owner=xap mode=0777
- name: "copy running script"
  copy: src={{newman_local_dir}}/ansible/roles/agent_deploy/files/newman-agent.sh dest={{agent_home_dir}} owner=xap mode=0777
- name: "start agents"
  shell: ./newman-agent.sh chdir="{{agent_home_dir}}"
  ignore_errors: yes