---
# This role installs newman server crontabs
- name: "start server after reboot"
  become: yes
  become_method: sudo
  cron: name="cronRunServer" special_time=reboot user=xap job=". /etc/environment; cd {{server_home_dir}}; ./run.sh"
  tags:
    - cron