---
# This playbook installs newman agent crontabs to monitor disk space and start agent after reboot
# Run it like that: ansible-playbook agents-crontabs.yml -i hosts -u xap

- hosts: newmanDockerAgents 
  remote_user: xap
  sudo: true
  vars:
    ansible_scripts_dir: /home/xap/ansible/scripts
  tasks:
      - name: create a dir for ansible scripts
        shell: mkdir -p {{ansible_scripts_dir}}
      - name: copy disk cleanup script to remote machines
        copy: src=files/diskSpace.sh dest={{ansible_scripts_dir}} owner=xap mode=0777
      - name: "add cron task to monitor disk space"
        cron: name="cronCleanDisk" minute=0 hour=6 user=xap job={{ansible_scripts_dir}}/diskSpace.sh
      - name: "start agent after reboot"
        cron: name="cronStartAgent" special_time=reboot user=xap job=/home/xap/newman-agent/newman-agent.sh