---
# This role installs newman submitter crontabs
- name: "start XAP submitter after reboot"
  become: yes
  become_method: sudo
  cron: name="cronRunSubmitter" special_time=reboot user=xap job=". /home/xap/.bashrc; cd {{submitter_home_dir}}; ./nohup-newman-submitter-loop.sh"
  tags:
    - cron
- name: "start INSIGHTEDGE submitter after reboot"
  become: yes
  become_method: sudo
  cron: name="cronRunIESubmitter" special_time=reboot user=xap job=". /home/xap/.bashrc; cd {{ie_submitter_home_dir}}; ./nohup-newman-submitter-loop.sh"
  tags:
    - cron