#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build 

# workaround github baseurl.
rm -rf _site/newman
mkdir  _site/newman
cp -r _site/stylesheets _site/newman/stylesheets
cp -r _site/update _site/newman/update
cp -r _site/js _site/newman/js



bundle exec htmlproof ./_site

rm -rf _site/newman
