---
# This playbook re-deploys newman agent
- name: "Install newman locally"
  hosts: 127.0.0.1
  connection: local
  roles:
    - newman_install
    - server_suspend
- name: "deploy newman docker agents"
  hosts: newmanDockerAgents
  remote_user: xap

  roles:
    - agent_deploy
    - agent_crontabs

#- name: "deploy newman tarzan ssd agents"
#  hosts: newmanTarzanServers
#  remote_user: tgrid

#  roles:
#    - tarzan_agent_deploy