---
# This playbook deploys new newman agents

- name: "Install newman locally+create ec2 instances + config file creation for ec2 machines"
  hosts: localhost
  connection: local
  roles:
    - agent_instance_creation_ec2


- name: "deploy EC2 docker agents"
  hosts: newNewmanDockerAgentsEC2
  remote_user: "{{ec2_newman_username}}"

  roles:
   - agent_instance_configuration_ec2_test
