---
# This playbook re-deploys/deploys newman submitter
- name: "Install newman locally"
  hosts: 127.0.0.1
  connection: local
  roles:
    - newman_install
    - deploy_submitter_jar
- name: "deploy/redeploy newman submitter"
  hosts: newmanSubmitter
  remote_user: xap

  roles:
    - submitter_deploy
    - ie_submitter_deploy
    - submitter_crontabs